In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
from sklearn.datasets import make_classification

In [6]:
#create dataset

In [10]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=123)

In [18]:
X

array([[ 0.24063119, -0.07970884, -0.05313268, ..., -0.09709308,
         0.06994683,  0.11660277],
       [ 0.75425016, -0.937854  ,  0.21947276, ...,  0.19311463,
        -2.27886416,  0.65102942],
       [ 0.9584009 , -1.31841143,  1.15350536, ...,  0.0423321 ,
         0.79249125,  0.24144309],
       ...,
       [ 0.72025002,  1.47831033, -1.28082896, ...,  1.68993071,
        -1.83623101,  0.11659189],
       [ 0.26260661, -0.83670259,  0.61205712, ..., -1.4899733 ,
         0.91494036,  1.58572634],
       [-0.10781378, -0.94865427,  0.17073559, ...,  0.24775547,
         1.99581849, -0.84668649]])

In [20]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.240631 -0.079709 -0.053133  0.092635 -0.139358  1.203193 -0.155900   
1    0.754250 -0.937854  0.219473 -1.280669  1.556185 -0.655390  0.770232   
2    0.958401 -1.318411  1.153505 -0.968165  1.886679  0.534737  0.460159   
3    0.643848  0.350821 -0.108697  0.710601 -0.854068  0.334855  0.607784   
4    1.032685 -1.264824  0.180678  0.359898 -0.263034 -0.337606  0.520756   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.184752 -0.171264 -0.708148  0.404388 -0.950816  0.865912  1.334531   
996 -0.690116 -0.847785 -1.110980  0.566567 -1.417596 -0.204183 -0.131628   
997  0.720250  1.478310 -1.280829  0.643484 -1.623729  0.519226 -0.672786   
998  0.262607 -0.836703  0.612057 -0.290582  0.757448  0.626942  0.054577   
999 -0.107814 -0.948654  0.170736  0.704442 -0.646387  0.558893 -1.389024   

            7         8         9  
0   -0.097093  0.069947  0.116603  
1    0.193115 -2.278864  0.651029  
2    0.042332  0.792491  0.241443  
3    0.948349  1.297784  2.165832  
4   -1.440363  1.257665  0.146308  
..        ...       ...       ...  
995  0.303720 -0.907488  1.243606  
996  0.822049 -1.574085  0.217518  
997  1.689931 -1.836231  0.116592  
998 -1.489973  0.914940  1.585726  
999  0.247755  1.995818 -0.846686  

[1000 rows x 10 columns]

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression

In [26]:
regression=LogisticRegression()
regression.fit(X_train,y_train)
y_pred=regression.predict(X_test)


In [28]:
y_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,

In [48]:
from sklearn.metrics import precision_score,accuracy_score,confusion_matrix,fbeta_score,recall_score,classification_report

In [32]:
accuracy_score(y_test,y_pred)

0.9454545454545454

In [34]:
precision_score(y_test,y_pred)

0.9567901234567902

In [38]:
fbeta_score(y_test,y_pred,beta=1)

0.9451219512195121

In [42]:
recall_score(y_test,y_pred)

0.9337349397590361

In [44]:
confusion_matrix(y_test,y_pred)

array([[157,   7],
       [ 11, 155]], dtype=int64)

In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95       164
           1       0.96      0.93      0.95       166

    accuracy                           0.95       330
   macro avg       0.95      0.95      0.95       330
weighted avg       0.95      0.95      0.95       330



In [54]:
# hyperparameter tuning

In [56]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1,0.1,0.2,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [66]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [64]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [60]:
#gridsearchcv
from sklearn.model_selection import GridSearchCV

In [68]:
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv)

In [70]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1, 0.1, 0.2, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [72]:
grid.fit(X_train,y_train)

C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\40000433\AppData

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1, 0.1, 0.2, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [74]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [76]:
grid.best_score_

0.953731343283582

In [82]:
y_pred=grid.predict(X_test)

In [84]:
accuracy_score(y_test,y_pred)

0.9303030303030303

In [86]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.95      0.93       164
           1       0.95      0.91      0.93       166

    accuracy                           0.93       330
   macro avg       0.93      0.93      0.93       330
weighted avg       0.93      0.93      0.93       330



In [90]:
# Randomized SearchCV

In [94]:
from sklearn.model_selection import RandomizedSearchCV
random=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')

In [96]:
random.fit(X_train,y_train)

C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
40 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\40000433\AppData\Local\anaconda3\Lib\site-packages\

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.2, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [102]:
y_pred=random.predict(X_test)

In [104]:
random.best_score_

0.9507462686567164

In [106]:
random.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 10}

In [108]:
accuracy_score(y_test,y_pred)

0.9454545454545454

In [110]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.93      0.96      0.95       164\n           1       0.96      0.93      0.95       166\n\n    accuracy                           0.95       330\n   macro avg       0.95      0.95      0.95       330\nweighted avg       0.95      0.95      0.95       330\n'

In [112]:
# Logistic regression for muticlass classification problem

In [116]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=3,random_state=123,n_informative=3)

In [122]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=33)

In [130]:
from sklearn.linear_model import LogisticRegression
logistic= LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [136]:
y_pred=logistic.predict(X_test)

In [138]:
confusion_matrix(y_test,y_pred)

array([[30, 35, 42],
       [38, 72, 10],
       [ 8, 10, 85]], dtype=int64)

In [142]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.39      0.28      0.33       107
           1       0.62      0.60      0.61       120
           2       0.62      0.83      0.71       103

    accuracy                           0.57       330
   macro avg       0.54      0.57      0.55       330
weighted avg       0.55      0.57      0.55       330

